name: Build Paintbrush Firmware

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Initialize West
        run: west init -l app

      - name: Update Modules
        run: west update

      - name: Build Left Half
        run: west build -p -b nice_nano_v2 -- -DSHIELD="the_paintbrush_left nice_oled"

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: paintbrush-left
          path: build/zephyr/zmk.uf2
